version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  products-service:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  orders-service:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  cart-service:
    build: ./cart-service
    ports:
      - "3004:3004"
    depends_on:
      - mongo
